name: Linting (Pull Request)
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  REALM_DISABLE_ANALYTICS: 1
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Java is needed to run the "./gradlew lint" command in the test app
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Install root package dependencies
        run: npm ci
      - name: Check types
        run: npm run check-types --workspace realm
      - name: Run linting of subpackages
        run: npm run lint
